spring.application.name=taskey
kartik.pro=m

# Aiven Live MySQL Database Details
spring.datasource.url=jdbc:mysql://mysql-1f58d99c-kartiktiwari216-aebb.a.aivencloud.com:19261/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_bu7E1n2iG230kUUYlk6
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Online deployment (Render) ke liye port setting
server.port=${PORT:8080}
